# Generated by Django 4.2.10 on 2024-02-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('playlist', models.URLField()),
                ('playlist_songs', models.JSONField()),
                ('depressed', models.BooleanField(default=False)),
                ('sad_percentage', models.FloatField()),
                ('happy_percentage', models.FloatField()),
                ('calm_percentage', models.FloatField()),
                ('energetic_percentage', models.FloatField()),
            ],
        ),
    ]
